"""Create initial schema for path_optimize module

Revision ID: 83d6e363514e
Revises: 
Create Date: 2025-11-15 01:39:33.188288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83d6e363514e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('average_duration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('segment_id', sa.String(length=100), nullable=False),
    sa.Column('departure_hour', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('avg_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('transport_type', sa.String(length=20), nullable=False),
    sa.Column('transport_name', sa.String(length=50), nullable=True),
    sa.Column('start_station_name', sa.String(length=100), nullable=True),
    sa.Column('end_station_name', sa.String(length=100), nullable=True),
    sa.Column('is_reliable', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('avg_duration_seconds > 0', name='duration_positive'),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6', name='day_range_valid'),
    sa.CheckConstraint('departure_hour >= 0 AND departure_hour <= 23', name='hour_range_valid'),
    sa.CheckConstraint('sample_count >= 0', name='sample_count_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_average_duration_segment_id'), 'average_duration', ['segment_id'], unique=False)
    op.create_index(op.f('ix_average_duration_updated_at'), 'average_duration', ['updated_at'], unique=False)
    op.create_index('ix_avg_duration_composite', 'average_duration', ['segment_id', 'departure_hour', 'day_of_week'], unique=False)
    op.create_table('commute_settings',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('home_address', sa.String(length=255), nullable=False),
    sa.Column('home_latitude', sa.Float(), nullable=False),
    sa.Column('home_longitude', sa.Float(), nullable=False),
    sa.Column('work_address', sa.String(length=255), nullable=False),
    sa.Column('work_latitude', sa.Float(), nullable=False),
    sa.Column('work_longitude', sa.Float(), nullable=False),
    sa.Column('target_arrival_time', sa.Time(), nullable=True),
    sa.Column('first_mile_duration', sa.Integer(), nullable=False),
    sa.Column('last_mile_duration', sa.Integer(), nullable=False),
    sa.Column('preference_routes', sa.JSON(), nullable=True),
    sa.Column('alert_start_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('first_mile_duration > 0', name='first_mile_positive'),
    sa.CheckConstraint('home_latitude >= -90 AND home_latitude <= 90', name='home_lat_valid'),
    sa.CheckConstraint('home_longitude >= -180 AND home_longitude <= 180', name='home_lon_valid'),
    sa.CheckConstraint('last_mile_duration > 0', name='last_mile_positive'),
    sa.CheckConstraint('work_latitude >= -90 AND work_latitude <= 90', name='work_lat_valid'),
    sa.CheckConstraint('work_longitude >= -180 AND work_longitude <= 180', name='work_lon_valid'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_commute_settings_user_id'), 'commute_settings', ['user_id'], unique=False)
    op.create_table('optimization_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('journey_date', sa.DateTime(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('suggested_route', sa.JSON(), nullable=True),
    sa.Column('selected_route', sa.JSON(), nullable=True),
    sa.Column('actual_arrival_time', sa.DateTime(), nullable=True),
    sa.Column('delay_occurred', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_optimization_history_composite', 'optimization_history', ['user_id', 'journey_date'], unique=False)
    op.create_index(op.f('ix_optimization_history_created_at'), 'optimization_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_optimization_history_journey_date'), 'optimization_history', ['journey_date'], unique=False)
    op.create_index(op.f('ix_optimization_history_user_id'), 'optimization_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_optimization_history_user_id'), table_name='optimization_history')
    op.drop_index(op.f('ix_optimization_history_journey_date'), table_name='optimization_history')
    op.drop_index(op.f('ix_optimization_history_created_at'), table_name='optimization_history')
    op.drop_index('ix_optimization_history_composite', table_name='optimization_history')
    op.drop_table('optimization_history')
    op.drop_index(op.f('ix_commute_settings_user_id'), table_name='commute_settings')
    op.drop_table('commute_settings')
    op.drop_index('ix_avg_duration_composite', table_name='average_duration')
    op.drop_index(op.f('ix_average_duration_updated_at'), table_name='average_duration')
    op.drop_index(op.f('ix_average_duration_segment_id'), table_name='average_duration')
    op.drop_table('average_duration')
    # ### end Alembic commands ###
